### ISSUE TITLE
Remove redundancies in /tools/browsers/ display

### ISSUE THREAD

**Issue by maxglycine** [soybase/jekyll-soybase#134]
The display of genomes has the DOI repeated for each genome from a paper.  
![Screenshot 2024-05-29 at 9 38 27 AM](https://github.com/soybase/jekyll-soybase/assets/14073707/699a0c00-283d-4250-91c8-a9faecd61127)

The DOI should be associated with the title example Liu, Du et al., 2020  _dx.doi.org/10.1016/j.cell.2929.05.023_
and not with each genome sequenced. This makes the page look busy and is redundant.

Should remove redundant references to the paper in genome titles ie.
"Genome assembly for Glycine max accession JiDouNo_17 (SoyC11) from Liu, Du et al. 2020." should be
"Genome assembly for Glycine max accession JiDouNo_17 (SoyC11)."
@jd-campbell @StevenCannon-USDA

**Comment by StevenCannon-USDA** [comment]
We can remove from Liu, Du et al. 2020 from the synopsis for each collection. The tradeoff is that the information won't be seen in the synopsis, which is displayed in other places, e.g.
https://dev.soybase.org/collections/ (genomes and annotations)
and
https://data.legumeinfo.org/Glycine/max/genomes/
and
https://data.legumeinfo.org/Glycine/max/annotations/

So, just confirming that you want this, @maxglycine. If so, I'll remove from all collections - or will delegate.

**Comment by maxglycine** [comment]
Well that would be very unfortunate.  I will take some time to try and understand the liquid and see what can be done. @StevenCannon-USDA @jd-campbell

**Comment by StevenCannon-USDA** [comment]
@maxglycine It's really just a problem for that one collection of genomes. I am not convinced it's something we should spend time on. A bit of redundancy in one part of a page, and it's not wrong; just busy.

**Comment by maxglycine** [comment]
@StevenCannon-USDA @jd-campbell 
Presentation is important.  Should we spend time on it now ... debatable.  Should we fix it on that page only ... yes

**Comment by StevenCannon-USDA** [comment]
@maxglycine OK. Probably can be handled with some special-casing on the contents of the variable `accession_group` from the file [description_Glycine_max.yml](https://github.com/legumeinfo/datastore-metadata/blob/main/Glycine/max/about_this_collection/description_Glycine_max.yml). Specifically: check if the contents contains ` 20`, which indicates a date string and hence a citation. In that case, don't print the DOI string for each genome description, but do print the DOI string under the `accession_group` heading (e.g. Liu, Du et al., 2020).

Should probably also remove e.g. "from Liu, Du et al. 2020" from each synopsis -- which is easy, but requires touching a lot of files.

The code for this browsers page is not straightforward, since it has to traverse the README files to find the corresponding genome+annotation sets and the synopsis. 

It may be time to "Consider writing a separate script that produces a _data/FILE.yml that is can be parsed/traversed with simpler liquid code." https://github.com/soybase/jekyll-soybase/issues/130
Contributors to this code have been @nathanweeks and @That-Thing

**Comment by StevenCannon-USDA** [comment]
Addressed in https://github.com/soybase/jekyll-soybase/pull/137. Closing.
