### ISSUE TITLE
Static Page: /collections data store links should be relative?

### ISSUE THREAD

**Issue by jd-campbell** [soybase/jekyll-soybase#62]
https://dev.soybase.org/resources/

**Comment by jd-campbell** [comment]
@maxglycine 

The group need more info to determine what are you asking here?

**Comment by maxglycine** [comment]
@jd-campbell It is hard to tell because of the use of liquid to do everything, but it appears that all of the links are created with an "absolute path"  i.e. "https://soybase.org/...".  Previously, Nathan @nathanweeks had us code everything with "relative paths" so if the code base changed servers i.e.  soybase-stage was moved to soybase, all the paths in the code would not have to be changed.  It looks like the YAML files use an absolute path for the URLs.  Should these be relative paths instead?  If we were to "give" the code base away, Those paths would not work and they would have to change every one of them to suit the new location.

**Comment by StevenCannon-USDA** [comment]
The links for the collections page are generated this way:
`<a target="_blank" href="{{ site.datastoreurl }}/{{ genus }}/{{ species }}/{{ datatype }}/">{{ datatype }}</a>`
The datastoreurl comes from a variable in `_config.yml`:
`datastoreurl: https://data.legumeinfo.org`

The link to the Data Store should be absolute, because it is "external" (though we maintain it).

So, I think this is as it should be. @maxglycine - let me know if I'm not looking at the right thing.

**Comment by jd-campbell** [comment]
Closed
